### ISSUE TITLE
set path to contract and public directory in the url

### ISSUE THREAD

**Issue by matteo-cristino** [ForkbombEu/ncr#97]
It should be possible to set a path prefix for both the contracts and the public directory url from ncr cli.

**Comment by puria** [comment]
Yeah I'm not sure why this is needed!
Why can't reflect the filesystem paths?

having a symbolic link inside the folder is not an option?


![Screenshot from 2024-03-12 at 15_29_07 981646022](https://github.com/ForkbombEu/ncr/assets/10379/bc5ffce0-9550-46d6-a4ee-12f7e1798a4b)

how do you see it?

**Comment by puria** [comment]
how do you see it, is the translitteration of "come la vedi?"

**Comment by puria** [comment]
No not move them
but link them `ln -s` like.

The thing is that ncr like restroom is file-routing based service. Means that the contract names and paths reflects the what is exposed online. If this became not true, then people will not figure out why getting 404 in place of serving the endpoint... maybe because the service have a `--prefix-public` imagine that defined inside a `.env` VERY hard to figure out and debug... come la vedi?

**Comment by puria** [comment]
But my very point is why we need the same contracts inside a folder and in another place... (I know you are trying to help me with the bug we faced yesterday) but the dyne zen philosophy here, should win over the functionalism ;p

**Comment by matteo-cristino** [comment]
We do not need the same contracts in two differenet folders, this is the whole point 😅 I think I'm not explaining me really well, let's try one final time and then I will close this ahahaha.

What I men is like if I have a project with multiple folder and I want the possibility to expose all of them or just one on a machine but keeping the same path for the urls in both case. To do that during the deploy of only one folder I should create a new folder (with the name of the parent folder) and then create a symbolic link for each file. I simply thought that instead of doing custom makefile that does the step above for each repo that we have with this format (see DIDRooom_microservices, mobile_zencode, W3C-DID, and maybe other in the future) it would have been easier to add this feature to ncr

**Comment by puria** [comment]
Yeah I get your point... I still stay on my... I think that doing an `ln -s ../* .` is not so much an hassle. 
But figuring out why your contract does not reply correctly and figure out that there where an option that changes the way you serve your endpoints is more dangerous ;( 

I forsee hours of debugging (because we are stupid people, always in rush, not perfectionists and doing a lot of context switch on many project in parallel) and so the ncr users... to finally found out that a prefix where defined somewhere :\

**Comment by matteo-cristino** [comment]
I get your point 🎯 then we will manage each directory in the most appropriate way 📂
